CREATE TABLE [dbo].[Tenants]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(255) NOT NULL, 
    [CompanyCode] NVARCHAR(50) NOT NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
